package tui

import (
	"strconv"
	"strings"

	"copperline/internal/model"

	ui "github.com/metaspartan/gotui/v5"
)

func (a *App) completeNick() bool {
	b := a.state.CurrentInfo()
	if b == nil || !model.IsChannel(b.Target) {
		a.resetNickCompletion()
		return false
	}

	text := []rune(a.input.Text)
	cursor := a.input.Cursor
	if cursor < 0 {
		cursor = 0
	}
	if cursor > len(text) {
		cursor = len(text)
	}

	// A second (or later) Tab cycles the matches generated by the first Tab.
	if len(a.nickCompletionMatches) > 0 &&
		a.nickCompletionStart >= 0 &&
		a.nickCompletionEnd >= a.nickCompletionStart &&
		a.nickCompletionEnd <= len(text) {
		a.nickCompletionIndex = (a.nickCompletionIndex + 1) % len(a.nickCompletionMatches)
		a.applyNickCompletion(text, a.nickCompletionMatches[a.nickCompletionIndex])
		return true
	}

	start := cursor
	for start > 0 && !isCompletionSeparator(text[start-1]) {
		start--
	}
	if start == cursor {
		return false
	}

	fragment := string(text[start:cursor])
	if fragment == "" {
		return false
	}

	end := cursor
	for end < len(text) && !isCompletionSeparator(text[end]) {
		end++
	}

	// Status prefixes are display metadata, not part of the nick itself. Accept
	// one if the user happened to type it, but complete to the real nickname.
	if len([]rune(fragment)) > 1 && strings.ContainsRune("~&@%+", []rune(fragment)[0]) {
		fragment = string([]rune(fragment)[1:])
		start++
	}
	if fragment == "" {
		return false
	}

	var matches []string
	needle := strings.ToLower(fragment)
	for _, nick := range a.irc.Names(b.Server, b.Target) {
		if strings.HasPrefix(strings.ToLower(nick), needle) {
			matches = append(matches, nick)
		}
	}
	if len(matches) == 0 {
		a.resetNickCompletion()
		return false
	}

	firstWord := start == 0
	if firstWord && end < len(text) && text[end] == ' ' {
		end++
	}

	a.nickCompletionMatches = matches
	a.nickCompletionIndex = 0
	a.nickCompletionStart = start
	a.nickCompletionEnd = end
	a.nickCompletionFirst = firstWord
	a.applyNickCompletion(text, matches[0])
	return true
}

func (a *App) applyNickCompletion(text []rune, nick string) {
	start := a.nickCompletionStart
	end := a.nickCompletionEnd
	if start < 0 || end < start || end > len(text) {
		a.resetNickCompletion()
		return
	}

	replacement := nick
	if a.nickCompletionFirst {
		replacement += ": "
	}
	repl := []rune(replacement)
	updated := make([]rune, 0, len(text)-(end-start)+len(repl))
	updated = append(updated, text[:start]...)
	updated = append(updated, repl...)
	updated = append(updated, text[end:]...)

	a.input.Text = string(updated)
	a.nickCompletionEnd = start + len(repl)
	a.input.Cursor = a.nickCompletionEnd
}

func (a *App) resetNickCompletion() {
	a.nickCompletionMatches = nil
	a.nickCompletionIndex = 0
	a.nickCompletionStart = -1
	a.nickCompletionEnd = -1
	a.nickCompletionFirst = false
}

func isCompletionSeparator(r rune) bool {
	return r == ' ' || r == '\t' || r == '\n' || r == '\r'
}

// handleJumpKey handles numbered buffer jumping after the configured jump key.
// Digits are collected until Enter. The configured cancel key aborts. Any
// unrelated key cancels jump mode and is then handled normally.
func (a *App) handleJumpKey(e ui.Event) bool {
	id := e.ID
	if keyBindingMatchesEvent(a.cfg.Keybindings.JumpBuffer, e) ||
		keyBindingMatchesEvent(a.cfg.Keybindings.JumpCancel, e) {
		a.jumpMode = false
		a.jumpDigits = ""
		return true
	}

	switch id {
	case "<Backspace>", "<C-h>":
		if len(a.jumpDigits) > 0 {
			a.jumpDigits = a.jumpDigits[:len(a.jumpDigits)-1]
		}
		return true
	case "<Enter>":
		digits := a.jumpDigits
		a.jumpMode = false
		a.jumpDigits = ""
		if digits == "" {
			return true
		}
		n, err := strconv.Atoi(digits)
		if err == nil && a.selectBufferNumber(n) {
			return true
		}
		if b := a.state.CurrentInfo(); b != nil {
			a.local(b.Server, b.Target, model.KindError, "no buffer numbered "+digits)
		}
		return true
	}

	if len(id) == 1 && id[0] >= '0' && id[0] <= '9' {
		// Buffer numbering starts at 1, so ignore leading zeroes.
		if id == "0" && a.jumpDigits == "" {
			return true
		}
		if len(a.jumpDigits) < 6 {
			a.jumpDigits += id
		}
		return true
	}

	// Do not steal any established keybinding.
	a.jumpMode = false
	a.jumpDigits = ""
	return false
}

func (a *App) selectBufferNumber(n int) bool {
	keys, _ := a.sidebarOrder()
	if n < 1 || n > len(keys) {
		return false
	}
	a.state.SelectKey(keys[n-1])
	a.follow = true
	return true
}

func (a *App) selectRelative(delta int) {
	keys, current := a.sidebarOrder()
	if len(keys) == 0 {
		return
	}

	idx := 0
	for i, key := range keys {
		if key == current {
			idx = i
			break
		}
	}
	idx = (idx + delta + len(keys)) % len(keys)
	a.state.SelectKey(keys[idx])
	a.follow = true
}

// sidebarOrder returns buffer keys in the exact order presented in the sidebar:
// each server buffer first, followed by that server's channels and queries in
// their stable creation order. Keyboard buffer navigation must use this same
// ordering so next/previous-buffer bindings never appear to jump randomly.
func (a *App) sidebarOrder() ([]string, string) {
	buffers, current := a.state.SnapshotInfo()
	servers := a.irc.ServerNames()
	keys := make([]string, 0, len(buffers))

	for _, server := range servers {
		serverKey := model.Key(server, "*server*")
		for _, b := range buffers {
			if model.Key(b.Server, b.Target) == serverKey {
				keys = append(keys, serverKey)
				break
			}
		}
		for _, b := range buffers {
			if b.Server == server && b.Target != "*server*" {
				keys = append(keys, model.Key(b.Server, b.Target))
			}
		}
	}

	return keys, current
}
