package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

type Config struct {
	General     GeneralConfig     `toml:"general"`
	Keybindings KeybindingsConfig `toml:"keybindings"`
	Theme       ThemeConfig       `toml:"theme"`
	DCC         DCCConfig         `toml:"dcc"`
	Gotify      GotifyConfig      `toml:"gotify"`
	Scripting   ScriptingConfig   `toml:"scripting"`
	Relay       RelayConfig       `toml:"relay"`
	Servers     []ServerConfig    `toml:"server"`
}

type GeneralConfig struct {
	Nick              string `toml:"nick"`
	User              string `toml:"user"`
	RealName          string `toml:"real_name"`
	Logging           *bool  `toml:"logging"`
	LogDir            string `toml:"log_dir"`
	Timestamp         string `toml:"timestamp"`
	Mouse             bool   `toml:"mouse"`
	ShowTyping        *bool  `toml:"show_typing"`
	SendTyping        *bool  `toml:"send_typing"`
	ShowJoinMessages  *bool  `toml:"show_join_messages"`
	HistoryLines      int    `toml:"history_lines"`
	InputHistoryLimit *int   `toml:"input_history_limit"`
	LogBacklogLines   *int   `toml:"log_backlog_lines"`
	ReconnectSecs     int    `toml:"reconnect_seconds"`
}

// KeybindingsConfig controls the main navigation/action shortcuts. Core text
// editing keys are reserved so rebinding navigation cannot make the input field
// unusable.
type KeybindingsConfig struct {
	NextBuffer         string `toml:"next_buffer"`
	PreviousBuffer     string `toml:"previous_buffer"`
	UserListDown       string `toml:"user_list_down"`
	UserListUp         string `toml:"user_list_up"`
	JumpBuffer         string `toml:"jump_buffer"`
	JumpCancel         string `toml:"jump_cancel"`
	CompleteNick       string `toml:"complete_nick"`
	HistoryPrevious    string `toml:"history_previous"`
	HistoryNext        string `toml:"history_next"`
	TranscriptPageUp   string `toml:"transcript_page_up"`
	TranscriptPageDown string `toml:"transcript_page_down"`
	TranscriptLineUp   string `toml:"transcript_line_up"`
	TranscriptLineDown string `toml:"transcript_line_down"`
	CopyMode           string `toml:"copy_mode"`
	FollowBottom       string `toml:"follow_bottom"`
	ClearInput         string `toml:"clear_input"`
	Quit               string `toml:"quit"`
	RelayReconnect     string `toml:"relay_reconnect"`
}

func (k *KeybindingsConfig) applyDefaults() {
	set := func(dst *string, value string) {
		if strings.TrimSpace(*dst) == "" {
			*dst = value
		}
	}
	set(&k.NextBuffer, "Ctrl+N")
	set(&k.PreviousBuffer, "Ctrl+P")
	set(&k.UserListDown, "Alt+N")
	set(&k.UserListUp, "Alt+P")
	set(&k.JumpBuffer, "F6")
	set(&k.JumpCancel, "Escape")
	set(&k.CompleteNick, "Tab")

	// Up/Down are now input-history navigation. Configs generated by older
	// Copperline releases commonly contain the old transcript defaults
	// explicitly; migrate those defaults so they do not conflict with history.
	if strings.TrimSpace(k.HistoryPrevious) == "" && strings.EqualFold(strings.TrimSpace(k.TranscriptLineUp), "Up") {
		k.TranscriptLineUp = "Alt+K"
	}
	if strings.TrimSpace(k.HistoryNext) == "" && strings.EqualFold(strings.TrimSpace(k.TranscriptLineDown), "Down") {
		k.TranscriptLineDown = "Alt+J"
	}
	set(&k.HistoryPrevious, "Up")
	set(&k.HistoryNext, "Down")
	set(&k.TranscriptPageUp, "PageUp")
	set(&k.TranscriptPageDown, "PageDown")
	set(&k.TranscriptLineUp, "Alt+K")
	set(&k.TranscriptLineDown, "Alt+J")
	set(&k.CopyMode, "Alt+L")
	set(&k.FollowBottom, "End")
	set(&k.ClearInput, "Ctrl+U")
	set(&k.Quit, "Ctrl+C")
	set(&k.RelayReconnect, "Alt+R")
}

func (k KeybindingsConfig) namedBindings() []struct {
	name  string
	value string
} {
	return []struct {
		name  string
		value string
	}{
		{"next_buffer", k.NextBuffer},
		{"previous_buffer", k.PreviousBuffer},
		{"user_list_down", k.UserListDown},
		{"user_list_up", k.UserListUp},
		{"jump_buffer", k.JumpBuffer},
		{"jump_cancel", k.JumpCancel},
		{"complete_nick", k.CompleteNick},
		{"history_previous", k.HistoryPrevious},
		{"history_next", k.HistoryNext},
		{"transcript_page_up", k.TranscriptPageUp},
		{"transcript_page_down", k.TranscriptPageDown},
		{"transcript_line_up", k.TranscriptLineUp},
		{"transcript_line_down", k.TranscriptLineDown},
		{"copy_mode", k.CopyMode},
		{"follow_bottom", k.FollowBottom},
		{"clear_input", k.ClearInput},
		{"quit", k.Quit},
	}
}

// CanonicalKeyBinding converts user-friendly config names and gotui event IDs
// to the same representation. Examples: Alt+N => <M-n>, Ctrl+P => <C-p>.
func CanonicalKeyBinding(value string) (string, error) {
	v := strings.TrimSpace(value)
	if v == "" {
		return "", errors.New("empty keybinding")
	}

	// Accept gotui/tcell-style event IDs directly.
	if strings.HasPrefix(v, "<") && strings.HasSuffix(v, ">") {
		inner := strings.TrimSpace(v[1 : len(v)-1])
		lower := strings.ToLower(inner)
		switch {
		case strings.HasPrefix(lower, "m-"):
			return canonicalModified("M", inner[2:])
		case strings.HasPrefix(lower, "a-"):
			return canonicalModified("M", inner[2:])
		case strings.HasPrefix(lower, "alt-"):
			return canonicalModified("M", inner[4:])
		case strings.HasPrefix(lower, "c-"):
			return canonicalModified("C", inner[2:])
		default:
			return canonicalNamed(inner)
		}
	}

	parts := strings.SplitN(v, "+", 2)
	if len(parts) == 2 {
		mod := strings.ToLower(strings.TrimSpace(parts[0]))
		key := strings.TrimSpace(parts[1])
		switch mod {
		case "ctrl", "control":
			return canonicalModified("C", key)
		case "alt", "meta":
			return canonicalModified("M", key)
		default:
			return "", fmt.Errorf("unsupported modifier %q", parts[0])
		}
	}

	if len([]rune(v)) == 1 {
		return v, nil
	}
	return canonicalNamed(v)
}

func canonicalModified(mod, key string) (string, error) {
	runes := []rune(strings.TrimSpace(key))
	if len(runes) != 1 {
		return "", fmt.Errorf("%s modifier requires a single key, got %q", mod, key)
	}
	r := runes[0]
	if r >= 'A' && r <= 'Z' {
		r += 'a' - 'A'
	}
	return fmt.Sprintf("<%s-%c>", mod, r), nil
}

func canonicalNamed(key string) (string, error) {
	k := strings.ToLower(strings.ReplaceAll(strings.TrimSpace(key), " ", ""))
	switch k {
	case "escape", "esc":
		return "<Escape>", nil
	case "enter", "return":
		return "<Enter>", nil
	case "tab":
		return "<Tab>", nil
	case "pageup", "pgup":
		return "<PageUp>", nil
	case "pagedown", "pgdown", "pgdn":
		return "<PageDown>", nil
	case "up":
		return "<Up>", nil
	case "down":
		return "<Down>", nil
	case "left":
		return "<Left>", nil
	case "right":
		return "<Right>", nil
	case "home":
		return "<Home>", nil
	case "end":
		return "<End>", nil
	case "backspace":
		return "<Backspace>", nil
	case "space":
		return "<Space>", nil
	}
	if len(k) >= 2 && k[0] == 'f' {
		if fn, err := strconv.Atoi(k[1:]); err == nil && fn >= 1 && fn <= 64 {
			return fmt.Sprintf("<F%d>", fn), nil
		}
	}
	return "", fmt.Errorf("unsupported key %q", key)
}

// KeyBindingMatches compares a configured binding with a gotui event ID.
func KeyBindingMatches(binding, eventID string) bool {
	want, err := CanonicalKeyBinding(binding)
	if err != nil {
		return false
	}
	got, err := CanonicalKeyBinding(eventID)
	return err == nil && want == got
}

func (g GeneralConfig) LoggingEnabled() bool {
	return g.Logging == nil || *g.Logging
}

func (g GeneralConfig) ShowTypingEnabled() bool {
	return g.ShowTyping == nil || *g.ShowTyping
}

func (g GeneralConfig) SendTypingEnabled() bool {
	return g.SendTyping == nil || *g.SendTyping
}

func (g GeneralConfig) ShowJoinMessagesEnabled() bool {
	return g.ShowJoinMessages == nil || *g.ShowJoinMessages
}

func (g GeneralConfig) InputHistoryLimitValue() int {
	if g.InputHistoryLimit == nil {
		return 10
	}
	return *g.InputHistoryLimit
}

func (g GeneralConfig) LogBacklogLinesValue() int {
	if g.LogBacklogLines == nil {
		return 10
	}
	if *g.LogBacklogLines < 0 {
		return 0
	}
	return *g.LogBacklogLines
}

type ThemeConfig struct {
	Background string   `toml:"background"`
	Panel      string   `toml:"panel"`
	Foreground string   `toml:"foreground"`
	Muted      string   `toml:"muted"`
	Border     string   `toml:"border"`
	Title      string   `toml:"title"`
	SelectedFG string   `toml:"selected_fg"`
	SelectedBG string   `toml:"selected_bg"`
	Timestamp  string   `toml:"timestamp"`
	Server     string   `toml:"server"`
	Channel    string   `toml:"channel"`
	Query      string   `toml:"query"`
	Unread     string   `toml:"unread"`
	Mention    string   `toml:"mention"`
	Notice     string   `toml:"notice"`
	Action     string   `toml:"action"`
	System     string   `toml:"system"`
	Error      string   `toml:"error"`
	DCC        string   `toml:"dcc"`
	Topic      string   `toml:"topic"`
	Input      string   `toml:"input"`
	CursorFG   string   `toml:"cursor_fg"`
	CursorBG   string   `toml:"cursor_bg"`
	StatusFG   string   `toml:"status_fg"`
	StatusBG   string   `toml:"status_bg"`
	NickColors []string `toml:"nick_colors"`
}

type DCCConfig struct {
	Enabled     bool   `toml:"enabled"`
	DownloadDir string `toml:"download_dir"`
	ListenAddr  string `toml:"listen_addr"`
	AdvertiseIP string `toml:"advertise_ip"`
}

type GotifyConfig struct {
	Enabled         bool   `toml:"enabled"`
	URL             string `toml:"url"`
	Token           string `toml:"token"`
	TokenEnv        string `toml:"token_env"`
	Mentions        *bool  `toml:"mentions"`
	PrivateMessages *bool  `toml:"private_messages"`
	Priority        *int   `toml:"priority"`
	TimeoutSeconds  int    `toml:"timeout_seconds"`
}

func (g GotifyConfig) MentionsEnabled() bool {
	return g.Mentions == nil || *g.Mentions
}

func (g GotifyConfig) PrivateMessagesEnabled() bool {
	return g.PrivateMessages == nil || *g.PrivateMessages
}

func (g GotifyConfig) PriorityValue() int {
	if g.Priority == nil {
		return 5
	}
	return *g.Priority
}

type ScriptingConfig struct {
	Enabled *bool  `toml:"enabled"`
	Dir     string `toml:"dir"`
}

func (s ScriptingConfig) EnabledValue() bool {
	return s.Enabled == nil || *s.Enabled
}

type RelayConfig struct {
	// Mode is one of "direct" (normal Copperline), "server" (headless IRC
	// relay with an embedded SSH server), or "client" (TUI connected to a
	// Copperline relay over SSH).
	Mode string `toml:"mode"`

	// Server mode.
	Listen         string `toml:"listen"`
	HostKey        string `toml:"host_key"`
	AuthorizedKeys string `toml:"authorized_keys"`

	// Client mode.
	Address                 string `toml:"address"`
	User                    string `toml:"user"`
	PrivateKey              string `toml:"private_key"`
	PrivateKeyPassphraseEnv string `toml:"private_key_passphrase_env"`
	HostKeyFingerprint      string `toml:"host_key_fingerprint"`
	InsecureSkipHostKey     bool   `toml:"insecure_skip_host_key_check"`
}

func (r RelayConfig) ModeValue() string {
	mode := strings.ToLower(strings.TrimSpace(r.Mode))
	if mode == "" {
		return "direct"
	}
	return mode
}

type ServerConfig struct {
	Name        string   `toml:"name"`
	Host        string   `toml:"host"`
	Port        int      `toml:"port"`
	TLS         bool     `toml:"tls"`
	SkipVerify  bool     `toml:"skip_verify"`
	Password    string   `toml:"password"`
	PasswordEnv string   `toml:"password_env"`
	Nick        string   `toml:"nick"`
	User        string   `toml:"user"`
	RealName    string   `toml:"real_name"`
	AutoConnect bool     `toml:"auto_connect"`
	Channels    []string `toml:"channels"`
	Caps        []string `toml:"caps"`
	SASL        SASL     `toml:"sasl"`
}

type SASL struct {
	Mechanism   string `toml:"mechanism"`
	Username    string `toml:"username"`
	Password    string `toml:"password"`
	PasswordEnv string `toml:"password_env"`
	Identity    string `toml:"identity"`
}

func DefaultPath() string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "copperline", "config.toml")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "config.toml"
	}
	return filepath.Join(home, ".config", "copperline", "config.toml")
}

func Load(path string) (*Config, error) {
	if path == "" {
		path = DefaultPath()
	}
	var cfg Config
	if _, err := toml.DecodeFile(path, &cfg); err != nil {
		return nil, err
	}
	cfg.applyDefaults()
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return &cfg, nil
}

func (c *Config) applyDefaults() {
	if c.General.Nick == "" {
		c.General.Nick = "copperline"
	}
	if c.General.User == "" {
		c.General.User = c.General.Nick
	}
	if c.General.RealName == "" {
		c.General.RealName = "Copperline IRC Client"
	}
	if c.General.Timestamp == "" {
		c.General.Timestamp = "15:04"
	}
	if c.General.HistoryLines <= 0 {
		c.General.HistoryLines = 1000
	}
	if c.General.ReconnectSecs <= 0 {
		c.General.ReconnectSecs = 10
	}
	if c.General.LogDir == "" {
		c.General.LogDir = "~/.local/state/copperline/logs"
	}
	c.Keybindings.applyDefaults()
	c.Theme.applyDefaults()
	if c.DCC.DownloadDir == "" {
		c.DCC.DownloadDir = "~/Downloads"
	}
	if c.DCC.ListenAddr == "" {
		c.DCC.ListenAddr = "0.0.0.0:0"
	}
	if c.Gotify.TimeoutSeconds <= 0 {
		c.Gotify.TimeoutSeconds = 5
	}
	if c.Scripting.Dir == "" {
		c.Scripting.Dir = "~/.config/copperline/scripts"
	}
	if c.Relay.Mode == "" {
		c.Relay.Mode = "direct"
	}
	if c.Relay.Listen == "" {
		c.Relay.Listen = "127.0.0.1:2222"
	}
	if c.Relay.HostKey == "" {
		c.Relay.HostKey = "~/.config/copperline/relay_host_ed25519"
	}
	if c.Relay.AuthorizedKeys == "" {
		c.Relay.AuthorizedKeys = "~/.config/copperline/relay_authorized_keys"
	}
	if c.Relay.User == "" {
		c.Relay.User = "copperline"
	}
	if c.Relay.PrivateKey == "" {
		c.Relay.PrivateKey = "~/.config/copperline/relay_client_ed25519"
	}
	for i := range c.Servers {
		s := &c.Servers[i]
		if s.Port == 0 {
			if s.TLS {
				s.Port = 6697
			} else {
				s.Port = 6667
			}
		}
		if s.Nick == "" {
			s.Nick = c.General.Nick
		}
		if s.User == "" {
			s.User = c.General.User
		}
		if s.RealName == "" {
			s.RealName = c.General.RealName
		}
		if s.SASL.Mechanism == "" && (s.SASL.Username != "" || s.SASL.Password != "" || s.SASL.PasswordEnv != "") {
			s.SASL.Mechanism = "plain"
		}
	}
}

func (t *ThemeConfig) applyDefaults() {
	set := func(dst *string, value string) {
		if *dst == "" {
			*dst = value
		}
	}

	// Copperline's built-in theme: dark navy panels with copper/aqua accents.
	set(&t.Background, "#090d16")
	set(&t.Panel, "#101827")
	set(&t.Foreground, "#d8dee9")
	set(&t.Muted, "#77839a")
	set(&t.Border, "#36506b")
	set(&t.Title, "#64d8cb")
	set(&t.SelectedFG, "#071018")
	set(&t.SelectedBG, "#d99058")
	set(&t.Timestamp, "#77839a")
	set(&t.Server, "#64d8cb")
	set(&t.Channel, "#8bd49c")
	set(&t.Query, "#d9a7ff")
	set(&t.Unread, "#f6c177")
	set(&t.Mention, "#ff9ecb")
	set(&t.Notice, "#f6c177")
	set(&t.Action, "#d9a7ff")
	set(&t.System, "#72c7ef")
	set(&t.Error, "#ff6b81")
	set(&t.DCC, "#8bd49c")
	set(&t.Topic, "#f2cc8f")
	set(&t.Input, "#eef1f6")
	set(&t.CursorFG, "#071018")
	set(&t.CursorBG, "#64d8cb")
	set(&t.StatusFG, "#071018")
	set(&t.StatusBG, "#64d8cb")
	if len(t.NickColors) == 0 {
		t.NickColors = []string{
			"#ff7b72", "#f6c177", "#8bd49c", "#64d8cb",
			"#72c7ef", "#d9a7ff", "#ff9ecb", "#d99058",
		}
	}
}

func isReservedInputKey(canonical string) bool {
	if len([]rune(canonical)) == 1 {
		return true
	}
	switch canonical {
	case "<Enter>", "<Backspace>", "<C-h>", "<Left>", "<Right>", "<Home>", "<Space>":
		return true
	default:
		return false
	}
}

func (c *Config) Validate() error {
	if c.General.InputHistoryLimit != nil && *c.General.InputHistoryLimit < 0 {
		return errors.New("[general].input_history_limit cannot be negative")
	}

	seenBindings := make(map[string]string)
	for _, binding := range c.Keybindings.namedBindings() {
		canonical, err := CanonicalKeyBinding(binding.value)
		if err != nil {
			return fmt.Errorf("[keybindings].%s: %w", binding.name, err)
		}
		if isReservedInputKey(canonical) {
			return fmt.Errorf("[keybindings].%s uses reserved input key %s", binding.name, binding.value)
		}
		if other, exists := seenBindings[canonical]; exists {
			return fmt.Errorf("[keybindings].%s conflicts with %s (%s)", binding.name, other, binding.value)
		}
		seenBindings[canonical] = binding.name
	}

	mode := c.Relay.ModeValue()
	switch mode {
	case "direct", "server", "client":
	default:
		return fmt.Errorf("[relay].mode must be direct, server, or client; got %q", c.Relay.Mode)
	}
	if mode == "client" {
		canonical, err := CanonicalKeyBinding(c.Keybindings.RelayReconnect)
		if err != nil {
			return fmt.Errorf("[keybindings].relay_reconnect: %w", err)
		}
		if isReservedInputKey(canonical) {
			return fmt.Errorf("[keybindings].relay_reconnect uses reserved input key %s", c.Keybindings.RelayReconnect)
		}
		if other, exists := seenBindings[canonical]; exists {
			return fmt.Errorf("[keybindings].relay_reconnect conflicts with %s (%s)", other, c.Keybindings.RelayReconnect)
		}
	}
	if mode == "server" {
		if strings.TrimSpace(c.Relay.Listen) == "" {
			return errors.New("[relay].listen is required in server mode")
		}
		if strings.TrimSpace(c.Relay.AuthorizedKeys) == "" {
			return errors.New("[relay].authorized_keys is required in server mode")
		}
	}
	if mode == "client" {
		if strings.TrimSpace(c.Relay.Address) == "" {
			return errors.New("[relay].address is required in client mode")
		}
		if strings.TrimSpace(c.Relay.PrivateKey) == "" {
			return errors.New("[relay].private_key is required in client mode")
		}
		if strings.TrimSpace(c.Relay.HostKeyFingerprint) == "" && !c.Relay.InsecureSkipHostKey {
			return errors.New("relay client requires [relay].host_key_fingerprint (or explicitly set insecure_skip_host_key_check = true)")
		}
	}

	if c.Gotify.Enabled {
		if strings.TrimSpace(c.Gotify.URL) == "" {
			return errors.New("gotify is enabled but [gotify].url is empty")
		}
		if strings.TrimSpace(Secret(c.Gotify.Token, c.Gotify.TokenEnv)) == "" {
			return errors.New("gotify is enabled but no application token is available; set token or token_env")
		}
	}
	if len(c.Servers) == 0 && mode != "client" {
		return errors.New("configuration contains no [[server]] entries")
	}
	seen := map[string]bool{}
	for _, s := range c.Servers {
		if strings.TrimSpace(s.Name) == "" {
			return errors.New("every server needs a name")
		}
		if seen[s.Name] {
			return fmt.Errorf("duplicate server name %q", s.Name)
		}
		seen[s.Name] = true
		if strings.TrimSpace(s.Host) == "" {
			return fmt.Errorf("server %q has no host", s.Name)
		}
	}
	return nil
}

func ExpandPath(path string) string {
	if path == "" {
		return path
	}
	if path == "~" || strings.HasPrefix(path, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			if path == "~" {
				return home
			}
			return filepath.Join(home, strings.TrimPrefix(path, "~/"))
		}
	}
	return path
}

func Secret(value, envName string) string {
	if envName != "" {
		if v := os.Getenv(envName); v != "" {
			return v
		}
	}
	return value
}
